[tools]
actionlint = "1.7.12"
dbmate = "2.35.0"
go = "1.27.1"
golangci-lint = "2.14.0"
node = "24"
pinact = "4.1.0"
sqlc = "1.31.1"
sqlite = "3.53.4"
terraform = "1.16.4"
tflint = "latest"

[env]
CGO_ENABLED = 1
PORT = { default = 8000 }

DATABASE_URL = { required = true, redact = true }
DBMATE_DRIVER = "sqlite3"
DBMATE_MIGRATIONS_DIR = "repository/migrations"
DBMATE_SCHEMA_FILE = "repository/schema.sql"
DBMATE_STRICT = "1"

OTEL_COLLECTOR_URL = { required = true }
GOOGLE_CLOUD_PROJECT_NAME = { required = true }

CORS_ALLOW_ORIGIN = { required = true }
USE_SECURE_COOKIE = "false"

[tasks."lint:go"]
run = ["go mod tidy -diff", "golangci-lint run"]

[tasks."lint:sqlc"]
run = ["sqlc diff", "sqlc vet"]

[tasks."lint:action"]
run = ["actionlint", "pinact run --check"]

[tasks."lint:terraform"]
run = ["terraform fmt -check", "tflint"]

[tasks.test]
run = [
    "go test -cover ./... -coverprofile=cover.out",
    "go tool cover -html=cover.out -o cover.html",
]

[tasks."image:build:app"]
usage = """
arg "version" default="latest"
"""
run = [
    "docker build --platform=linux/amd64 --tag asia-northeast1-docker.pkg.dev/tasks-510111/tasks/app:${usage_version?} -f infrastructure/app/Dockerfile ."
]

[tasks."image:push:app"]
usage = """
arg "version" default="latest"
"""
run = [
    "docker push asia-northeast1-docker.pkg.dev/tasks-510111/tasks/app:${usage_version?}"
]

[tasks."image:build:otelcol"]
usage = """
arg "version" default="latest"
"""
run = [
    "docker build --platform=linux/amd64 --tag asia-northeast1-docker.pkg.dev/tasks-510111/tasks/otelcol:${usage_version?} -f infrastructure/otelcol/Dockerfile ."
]

[tasks."image:push:otelcol"]
usage = """
arg "version" default="latest"
"""
run = [
    "docker push asia-northeast1-docker.pkg.dev/tasks-510111/tasks/otelcol:${usage_version?}"
]
