// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package repository

import (
	"context"
)

const listStatuses = `-- name: ListStatuses :many
SELECT name FROM statuses ORDER BY name ASC
`

func (q *Queries) ListStatuses(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
