name: sqldef
run-name: sqldef
on:
  pull_request:
jobs:
  preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - name: preview-sqldef
        uses: sqldef/sqldef-preview-action@c02e888491ec4560b9ade14df5fe5b7a40df44dc # v1
        with:
          command: sqlite3def
          version: v3.11.26
          schema-file: schema.sql
          sqlite-database: test.db
          github-token: ${{ env.GITHUB_TOKEN }}
